### ISSUE TITLE
Ошибки в консоли и css

### ISSUE THREAD

**Issue by Cactusx09** [markello-git/markhost#3]
![image](https://cloud.githubusercontent.com/assets/9021479/20076331/b3392020-a540-11e6-86ac-b0de024dc459.png)

**Посмотри ,пожалуйста, эти ошибки** 
(может это и я напартачил где-то когда танцевал с мержом веток)

![image](https://cloud.githubusercontent.com/assets/9021479/20076398/ea6d9134-a540-11e6-8713-b30e740ab7d9.png)

**Comment by markello-git** [comment]
консольная ошибка это google map. API подключен, а нигде неиспользуется потомучто
